version: "3.8"

services:
  ingestion:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: dados_coingecko_ingestion
    environment:
      FUNCTION: "ingestion"
      RAW_PATH: /app/AWS/S3/RAW/
      WORK_PATH: /app/AWS/S3/WORK/
      RAW_CONFIG: /app/assets/config.ingestion.json
      WORK_CONFIG: /app/assets/config.preparation.json
    volumes:
      - ..:/app

  preparation:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: dados_coingecko_preparation
    environment:
      FUNCTION: "preparation"
      RAW_PATH: /app/AWS/S3/RAW/
      WORK_PATH: /app/AWS/S3/WORK/
      RAW_CONFIG: /app/assets/config.ingestion.json
      WORK_CONFIG: /app/assets/config.preparation.json
    volumes:
      - ..:/app
