version: "3.8"

services:
  ingestion:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: dados_coingecko_ingestion
    environment:
      RAW_PATH: ${RAW_PATH_DOCKER}
      WORK_PATH: ${WORK_PATH_DOCKER}
      RAW_CONFIG: ${RAW_CONFIG_DOCKER}
      WORK_CONFIG: ${WORK_CONFIG_DOCKER}
    volumes:
      - shared-data:/app/AWS/S3/RAW
    command: ["python", "-c", "from app import ingestion_handler; ingestion_handler({'subsource': 'coingecko'})"]

  preparation:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: dados_coingecko_preparation
    depends_on:
      - ingestion
    environment:
      RAW_PATH: ${RAW_PATH_DOCKER}
      WORK_PATH: ${WORK_PATH_DOCKER}
      RAW_CONFIG: ${RAW_CONFIG_DOCKER}
      WORK_CONFIG: ${WORK_CONFIG_DOCKER}
    volumes:
      - shared-data:/app/AWS/S3/RAW
    command: ["python", "-c", "from app import preparation_handler; preparation_handler({'subsource': 'coingecko'})"]

volumes:
  shared-data:
    driver: local